## Missing values data check
https://www.kaggle.com/noriuk/us-education-datasets-unification-project

In [55]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import warnings

In [56]:
!pip install psycopg2

Requirement already satisfied: psycopg2 in /opt/anaconda3/lib/python3.11/site-packages (2.9.9)

In [57]:

engine = create_engine('postgresql://{}:{}@{}:{}/{}'.format(
    postgres_user, postgres_pw, postgres_host, postgres_port, postgres_db))

ed2_df = pd.read_sql_query('SELECT * FROM useducation',con=engine)

In [58]:

ed2_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1492 entries, 0 to 1491
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   PRIMARY_KEY                   1492 non-null   object
 1   STATE                         1492 non-null   object
 2   YEAR                          1492 non-null   int64
 3   ENROLL                        1229 non-null   float64
 4   TOTAL_REVENUE                 1280 non-null   float64
 5   FEDERAL_REVENUE               1280 non-null   float64
 6   STATE_REVENUE                 1280 non-null   float64
 7   LOCAL_REVENUE                 1280 non-null   float64
 8   TOTAL_EXPENDITURE             1280 non-null   float64
 9   INSTRUCTION_EXPENDITURE       1280 non-null   float64
 10  SUPPORT_SERVICES_EXPENDITURE  1280 non-null   float64
 11  OTHER_EXPENDITURE             1229 non-null   float64
 12  CAPITAL_OUTLAY_EXPENDITURE    1280 non-null   float64
 13  GRADES_PK_G                   1319 non-null   float64
 14  GRADES_KG_G                   1360 non-null   float64
 15  GRADES_4_G                    1361 non-null   float64
 16  GRADES_8_G                    1361 non-null   float64
 17  GRADES_12_G                   1361 non-null   float64
 18  GRADES_1_8_G                  1361 non-null   float64
 19  GRADES_9_12_G                 1361 non-null   float64
 20  GRADES_ALL_G                  1319 non-null   float64
 21  AVG_MATH_4_SCORE              536 non-null    float64
 22  AVG_MATH_8_SCORE              532 non-null    float64
 23  AVG_READING_4_SCORE           533 non-null    float64
 24  AVG_READING_8_SCORE           498 non-null    float64
dtypes: float64(22), int64(1), object(2)
memory usage: 291.5+ KB

In [59]:
ed2_df.head()

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,NaN,2678885.0,304177.0,1659028.0,715680.0,2653798.0,1481703.0,...,57948.0,58025.0,41167.0,471564.0,196386.0,676174.0,208.327876,252.187522,207.963517,NaN
1,1992_ALASKA,ALASKA,1992,NaN,1049591.0,106780.0,720711.0,222100.0,972488.0,498362.0,...,9748.0,8789.0,6714.0,79117.0,30847.0,112335.0,NaN,NaN,NaN,258.859712
2,1992_ARIZONA,ARIZONA,1992,NaN,3258079.0,297888.0,1369815.0,1590376.0,3401580.0,1435908.0,...,55433.0,49081.0,37410.0,437127.0,175210.0,614881.0,215.253932,265.366278,206.212716,262.169895
3,1992_ARKANSAS,ARKANSAS,1992,NaN,1711959.0,178571.0,958785.0,574603.0,1743022.0,964323.0,...,34632.0,36011.0,27651.0,281338.0,123113.0,405259.0,210.206028,256.312090,208.634458,264.619665
4,1992_CALIFORNIA,CALIFORNIA,1992,NaN,26260025.0,2072470.0,16546514.0,7641041.0,27138832.0,14358922.0,...,418418.0,363296.0,270675.0,3286034.0,1372011.0,4717112.0,208.398961,260.892247,196.764414,NaN

In [60]:
ed2_df.isnull()

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,True,True,True,False
2,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1487,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,False,False,False
1488,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,False,False,False
1489,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,False,False,False
1490,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,False,False,False
1491,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,False,False,False

In [61]:
for column_name in ed2_df.columns:
    print("Unique values in column {} are: {}".format(column_name, ed2_df[column_name].unique()))

Unique values in column PRIMARY_KEY are: ['1992_ALABAMA' '1992_ALASKA' '1992_ARIZONA' ... '2017_WEST_VIRGINIA'
 '2017_WISCONSIN' '2017_WYOMING']
Unique values in column STATE are: ['ALABAMA' 'ALASKA' 'ARIZONA' 'ARKANSAS' 'CALIFORNIA' 'COLORADO'
 'CONNECTICUT' 'DELAWARE' 'DISTRICT_OF_COLUMBIA' 'FLORIDA' 'GEORGIA'
 'HAWAII' 'IDAHO' 'ILLINOIS' 'INDIANA' 'IOWA' 'KANSAS' 'KENTUCKY'
 'LOUISIANA' 'MAINE' 'MARYLAND' 'MASSACHUSETTS' 'MICHIGAN' 'MINNESOTA'
 'MISSISSIPPI' 'MISSOURI' 'MONTANA' 'NEBRASKA' 'NEVADA' 'NEW_HAMPSHIRE'
 'NEW_JERSEY' 'NEW_MEXICO' 'NEW_YORK' 'NORTH_CAROLINA' 'NORTH_DAKOTA'
 'OHIO' 'WYOMING' 'OKLAHOMA' 'OREGON' 'PENNSYLVANIA' 'RHODE_ISLAND'
 'SOUTH_CAROLINA' 'SOUTH_DAKOTA' 'TENNESSEE' 'TEXAS' 'UTAH' 'VERMONT'
 'VIRGINIA' 'WASHINGTON' 'WEST_VIRGINIA' 'WISCONSIN'
 'BUREAU_OF_INDIAN_AFFAIRS' 'DOD_OVERSEAS' 'DOD_DOMESTIC' 'AMERICAN_SAMOA'
 'GUAM' 'NORTHERN_MARIANAS' 'PUERTO_RICO' 'VIRGIN_ISLANDS' 'BI' 'DD'
 'NORTHERN_MARIANA_ISLANDS' 'DEPARTMENT_OF_DEFENSE'
 'BUREAU_OF_INDIAN_EDUCATION' 'DEPARTMENT_OF_DEFENSE_EDUCATION_ACTIVITY'
 'U.S._VIRGIN_ISLANDS' 'DOD_(OVERSEAS_AND_DOMESTIC_COMBINED)' 'BIE'
 'DOD_-_FOREIGN' 'COMMONWEALTH_OF_MARIANAS' 'AS' 'GU' 'MP' 'PR' 'VI'
 'MARIANAS' 'BUREAU_OF_INDIAN_EDUCATIO' 'DOD_-_OVERSEAS' 'DOD_-_DOMESTIC'
 'DOD']
Unique values in column YEAR are: [1992 2001 1993 2016 1994 1995 1996 1997 1998 1999 2017 2000 2002 2003
 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015]
Unique values in column ENROLL are: [     nan   89711.  727716. ... 1462036.  108384. 1595024.]
Unique values in column TOTAL_REVENUE are: [ 2678885.  1049591.  3258079. ... 13448045.  1788749. 23766529.]
Unique values in column FEDERAL_REVENUE are: [ 304177.  106780.  297888. ... 1557900.  155453. 1680983.]
Unique values in column STATE_REVENUE are: [1659028.  720711. 1369815. ... 8287126.  985365. 9277802.]
Unique values in column LOCAL_REVENUE are: [  715680.   222100.  1590376. ...  3603019.   647931. 12807744.]
Unique values in column TOTAL_EXPENDITURE are: [ 2653798.   972488.  3401580. ... 14207389.  1963630. 23352516.]
Unique values in column INSTRUCTION_EXPENDITURE are: [ 1481703.   498362.  1435908. ...  8060544.   867650. 12247509.]
Unique values in column SUPPORT_SERVICES_EXPENDITURE are: [ 735036.  350902. 1007732. ... 4102549.  474679. 7357292.]
Unique values in column OTHER_EXPENDITURE are: [    nan  24913. 237222. ... 754102. 117979. 956321.]
Unique values in column CAPITAL_OUTLAY_EXPENDITURE are: [ 174053.   37451.  609114. ...  912783.  412047. 1854842.]
Unique values in column GRADES_PK_G are: [8224. 2371. 2544. ... 1369.  570.  270.]
Unique values in column GRADES_KG_G are: [55460. 10152. 53497. ...   632. 31976.  1006.]
Unique values in column GRADES_4_G are: [57948.  9748. 55433. ...   862. 38583.  1212.]
Unique values in column GRADES_8_G are: [58025.  8789. 49081. ...   823. 39143.  1103.]
Unique values in column GRADES_12_G are: [41167.  6714. 37410. ...   635. 29374.  1024.]
Unique values in column GRADES_1_8_G are: [471564.  79117. 437127. ...   6595. 305453.   9403.]
Unique values in column GRADES_9_12_G are: [196386.  30847. 175210. ...   3218. 140785.   5084.]
Unique values in column GRADES_ALL_G are: [676174. 112335. 614881. ... 550419.  10275. 446508.]
Unique values in column AVG_MATH_4_SCORE are: [208.32787592          nan 215.25393202 210.2060281  208.39896092
 221.02342908 226.79848004 217.89997245 192.60055314 213.68975116
 215.59490616 214.05666607 221.56253449 221.03774247 229.8840779
 215.04815772 204.14021133 231.63883994 217.31770794 226.59791778
 219.8783523  228.49359628 201.82826119 222.21559976 225.33264753
 229.66456384 227.14804704 213.29908987 218.44553529 212.88448989
 228.66281534 218.71193488 220.31980592 224.30573158 215.44924815
 212.49671381 210.94822741 217.91874445 224.04224767 220.76296422
 215.26892842 228.69200112 225.37759164 211.64697355 223.83345456
 217.57594048 215.846436   209.12908268 225.80585754 232.02657385
 215.02510174 187.13466996 215.76358264 215.45586175 214.96556159
 229.39444359 229.1261984  219.98819498 209.02067003 232.20704455
 220.69496067 228.96640259 226.25805639 232.1930884  208.43411858
 224.73446178 227.51623615 227.54399273 217.62261218 227.24016718
 213.84402497 222.6340587  224.32512494 230.90418316 223.47616473
 226.21201467 220.41809392 213.19441492 219.17624798 228.7129198
 226.51584124 224.88106013 222.643213   225.05329812 223.35013275
 231.41185148 223.19600293 237.5549343  217.94105296 218.76661906
 217.06286951 213.56512505 234.24337473 193.28977448 219.55675713
 215.84679855 226.8937845  224.9304113  234.42142885 232.89693492
 231.95343458 220.99359666 217.96375619 230.568646   222.31040682
 234.95961325 230.88697249 235.27088758 210.97035028 228.55281381
 229.81200483 225.94533582 220.27486645 213.86830075 226.55906072
 232.46306483 230.8929578  230.57421661 225.04192224 226.62949114
 224.63385726 220.41700623 219.8355873  232.66602972 227.2926732
 231.69773638 230.39480893 224.84829807 229.25192274 223.34464264
 232.99165432 228.91139607 229.00658866 227.4549818  235.19311612
 240.61524163 235.85942455 204.91985043 233.72881146 230.2549768
 226.83461021 234.9437647  232.85677529 237.96827989 238.47669455
 241.74736576 228.72634326 226.24772912 237.61571038 233.07985229
 234.04399297 241.66452743 235.68697467 241.91229558 222.89060051
 234.83642535 235.75491527 236.25410841 227.51359831 243.1101422
 238.7765412  222.51800924 235.93007548 242.04012561 237.57738683
 237.7820679  229.09662128 236.30590557 235.94701712 230.29796199
 235.79322354 237.26482055 227.75504472 237.30592183 234.78295087
 241.92607242 239.20308912 238.29283947 230.76774845 236.75541398
 241.08570065 225.07123624 235.51070554 229.80067307 235.54546696
 230.3669575  239.21587446 242.12073236 239.71691238 211.12229853
 238.9306496  233.63573779 230.0968754  241.65011574 233.06749397
 240.06909881 239.88080181 245.78204649 231.49230537 230.23119641
 240.69145968 238.42170674 247.33704896 237.70600299 245.74619113
 226.69884472 235.03554762 240.57548855 237.70617848 229.87159551
 245.6259264  243.9789314  224.02721826 238.1739767  241.23554933
 242.73699506 242.10593522 233.9553288  238.32493057 240.57296331
 233.43677231 238.30267533 241.59418608 231.68807971 241.99091632
 238.79742376 243.52885539 240.49756818 241.68467452 230.84326792
 240.56858192 242.95591377 228.52001797 237.27389322 231.93693355
 237.67068744 230.03409123 240.20589025 242.75564683 241.79489489
 213.69889881 242.02025002 235.20901709 234.28613498 240.90284354
 237.28704132 245.14425496 242.8195893  247.92365419 235.08792019
 230.04311925 242.37060398 240.32823069 252.43031979 237.60555347
 246.99776241 227.61237708 239.41110289 243.61881126 238.04080864
 231.78160051 248.57152656 248.62152237 228.06431284 242.54301818
 241.61799402 245.41585417 244.53273171 236.80219419 236.0396573
 244.00127349 235.87793575 237.10741145 241.21342858 232.75371011
 242.33975986 239.40498891 246.35740496 243.52112978 242.54223198
 236.3378058  244.1812142  243.86691506 227.96265041 237.21228434
 229.99110522 237.54059191 231.67492721 243.13244    244.71774273
 239.49056944 219.26014103 241.94490938 236.02957289 235.67978083
 241.0428023  238.28566885 242.61680956 242.595644   245.30865357
 238.83590231 229.43245545 244.45573275 243.79504103 252.2547897
 236.27971974 249.45553421 227.26226085 240.68438094 244.40075191
 238.74846336 241.58894696 235.15227389 251.07175263 246.52986978
 230.02958925 240.64109876 243.77846013 245.18952627 243.68755286
 236.78098559 238.03232725 243.58787315 238.76685909 235.66830248
 242.09778976 231.8254862  240.46462371 240.31871262 247.76722605
 243.07129689 242.25709121 232.98314449 243.58525352 242.00919568
 231.28601904 236.35965803 235.15759705 237.81015698 234.16499321
 244.45609711 242.4134069  240.35983243 221.80828312 239.82645104
 238.36654209 238.82192776 240.32883247 238.83687893 243.83687597
 242.60487295 246.25533479 240.83070024 230.77886927 244.25701654
 247.10655581 253.39645576 236.40221371 249.18668615 229.86802222
 240.49483104 243.79660654 239.80326865 237.03187887 251.77883682
 248.00416256 232.84037073 237.51994262 244.51790076 245.15641599
 244.03862155 237.42908227 236.91449705 245.65491029 241.62477468
 237.30302498 240.97979226 232.90111698 241.10179365 242.53751311
 246.63972992 245.33361814 243.18288466 234.65580676 244.69186552
 243.87443503 237.32627023 232.86133247 233.13245999 236.12200442
 240.30491147 239.8905221  233.65446462 246.97570803 243.44029739
 243.10775818 228.56725387 241.67580957 240.04723665 243.30861894
 240.72201984 239.00020402 248.59677736 245.79350555 246.18570187
 241.46992679 231.36630864 245.8470018  245.16937955 253.0337852
 236.8197784  253.42096113 231.10572141 239.54836193 243.69888459
 243.15792913 236.26289939 252.99352517 246.8709092  232.78143293
 240.34981687 244.80173289 246.42479489 245.54979691 238.92187748
 240.09925202 244.01261996 241.41673524 236.62589974 240.98109972
 239.77478702 241.92628874 242.82068873 247.80329474 246.17745694
 246.28833807 237.44063266 244.70629165 246.52240092 230.97742266
 236.32841695 237.61175543 235.21546973 231.54934501 241.56357562
 240.15946886 238.67801882 231.30752512 242.66432093 236.45251926
 237.89580684 238.79962471 237.30781379 247.65218362 243.33991187
 241.06720852 241.72776193 234.28190183 242.2446541  239.49975091
 250.56577783 235.72889369 249.57584695 234.24305314 238.9649225
 241.28704826 243.86366688 233.82701621 249.15062135 245.38322008
 231.16723596 236.79692704 243.74226679 244.71383058 243.5985912
 239.76048145 237.74670894 243.31223994 238.00172968 237.08957146
 239.72309495 240.66739574 244.00247204 242.56278706 243.25039916
 246.61262171 244.98142219 235.20466146 243.31021132 246.75976447
 241.67232721 232.17068774 230.45627756 234.43578815 233.84814368
 232.26294099 240.69501662 239.2376509  236.12756171 231.32046215
 246.36769578 236.38360303 237.91976874 239.96751408 238.11894744
 246.51375006 243.10748436 241.21280457 239.17825741 228.9717454
 239.89899452 240.60127732 249.10267391 235.55547255 248.80430257
 234.69419303 239.50228916 240.7216345  245.59067459 231.68516216
 245.31983857 247.85523118 229.70428194 235.54845726 240.95139307
 244.24351526 240.9283721  236.69251538 240.94367067 242.48076625
 240.89329719 248.04105906 241.70100097 236.05701891 240.38921339
 247.82061921]
Unique values in column AVG_MATH_8_SCORE are: [252.18752241          nan 265.36627779 256.31209042 260.89224682
 272.39843291 273.73934457 262.8685854  234.92462133 259.90884818
 259.35943359 257.41088741 275.09029414 270.09894394 283.36000904
 262.24128164 249.98392592 278.63538412 264.82549311 272.78320127
 267.35319433 282.39220464 246.45803543 271.13154474 277.65452338
 278.21632559 271.90556119 259.60671765 266.4223001  258.40537481
 283.21307471 268.12419783 268.13198963 271.37843878 265.90710912
 260.772544   258.82804812 264.59282838 274.34317714 267.86372628
 259.08644839 277.87913461 275.08007605 256.59486321 277.64307145
 267.87483434 261.65274525 262.77247844 275.60821425 279.59124485
 266.73367332 232.83150953 263.6393936  262.46602094 262.13008166
 275.5290368  283.9863686  266.59168402 252.3803947  284.05985743
 269.68143144 277.56564205 276.86607825 284.04894463 250.21548908
 273.28488724 283.00386996 282.76960686 261.97036672 270.23148604
 267.83456028 284.22226798 276.34151319 268.87730813 260.77544755
 263.11893503 270.19957756 276.77310581 279.25324301 269.75440471
 276.11711956 264.86520544 282.84874172 274.77894698 277.18012565
 262.15820552 270.7154059  261.36371267 262.17102659 281.90248556
 234.42879806 266.33204732 262.77256054 277.91791354 276.90945905
 283.05122926 283.67961915 271.5615114  258.98200182 283.64170358
 276.01436006 283.12324555 278.45266671 287.65194219 254.03390027
 273.57578041 286.58460702 280.6180687  268.18159912 259.84467304
 276.26285877 280.1279472  283.07384405 282.67275353 271.6457939
 280.6402228  273.4257851  266.35369953 263.43659969 274.84601594
 275.43670993 283.40838145 276.67499154 270.78007629 276.68998034
 261.93902223 279.02506987 271.17735048 265.77158934 267.04950059
 283.39985848 283.72981121 277.15836893 243.05963825 271.37149024
 269.67700923 265.72858102 279.93926684 277.16008096 281.22093976
 283.95334474 284.19108805 274.27847217 266.32835927 281.90377332
 277.71611251 274.67382112 286.52069448 276.4418616  290.68005598
 260.91193358 278.76625035 285.92802255 282.19375597 268.04313771
 286.19846866 281.4071199  263.27290665 279.74925704 281.24035057
 287.14464048 281.60729538 271.90515135 280.89247091 278.53775812
 271.99869438 277.30044962 284.88173638 268.17572856 277.05264895
 280.64536966 285.64557218 281.67664337 281.15136441 270.77035345
 283.91586565 283.50334994 262.21110005 278.95870939 274.30509005
 271.63634837 268.55812858 280.82400731 281.06895301 280.95354283
 245.21578077 274.0483769  272.19156441 265.62931911 280.96689665
 277.67223891 281.71494554 283.81092883 284.03005348 273.98302716
 267.75503085 281.05854092 277.93079458 291.51354112 277.34668196
 290.07499579 262.45624271 276.44993926 286.43200122 283.96299104
 269.9055855  285.25335704 283.90260424 263.27516299 279.7162537
 281.82513659 286.96095344 283.25177471 271.35990241 282.23732536
 280.71383507 272.34501807 281.23432114 287.30361798 270.52457678
 281.10284505 279.15612343 287.35648762 284.37162822 285.05222973
 269.0994928  284.54155658 282.1006096  266.00010992 282.55715412
 275.54842641 273.89986216 270.38178401 286.19275617 282.47279006
 282.99208274 248.19874242 277.38349726 274.77866464 268.77201335
 283.50759577 280.49709603 285.0072109  285.22690315 290.03259983
 278.70474991 272.3862996  286.47225312 285.73426524 297.92334448
 276.83051708 291.85111654 264.8909187  280.61953829 287.07552895
 283.65059865 270.80402437 287.55706095 288.58345145 267.53807866
 280.14117724 283.88066876 291.56161192 284.85163947 274.53498935
 283.8262772  286.16686333 275.38699047 281.50360148 288.46392527
 273.97878662 285.87070842 281.08747371 291.01077379 287.62590496
 284.86280434 270.08409359 285.61794252 286.98777148 268.52412032
 283.0476628  277.33228196 275.99949999 270.44858815 287.37290752
 288.60851345 283.82947298 253.59518687 279.33526411 277.56119973
 273.75860668 287.30521505 282.43141699 286.80997789 284.17017855
 288.59640304 279.28421609 272.3799067  286.36142594 288.3415653
 298.85434662 278.26816815 294.44332011 265.00195815 285.80800195
 291.54294288 284.25909353 286.37615953 274.14854168 292.32181722
 292.65722711 269.7042538  282.57691542 284.33263525 292.84248854
 285.58301378 275.71195683 285.03681437 288.30416892 277.92371937
 280.38085541 290.61912771 274.76182109 286.68507668 284.06825187
 292.86609635 286.06975499 288.72237561 270.41576592 288.14072624
 286.10403399 269.09651584 283.27279787 279.03350171 279.08820502
 272.76980309 291.74267287 286.99994469 282.7699664  260.46687785
 277.83703521 278.48361919 277.83621105 286.67506325 283.22813469
 285.00291609 284.92083606 289.61928267 281.60880971 272.84333389
 288.73229764 287.99780226 298.51243111 280.17651797 294.94642281
 269.23564562 281.94764625 292.90780428 283.19704484 278.11315373
 292.10873974 294.13877137 274.45470146 280.45302609 286.26702824
 291.99840449 288.60259683 279.17960819 282.51820678 286.10274174
 282.87565962 281.00013372 290.61519679 274.03871032 290.34670936
 283.30833209 293.88257707 289.25541115 288.10776195 273.26317312
 288.66593269 287.76792605 274.68888341 269.19428062 282.17302844
 281.55957284 279.72226796 277.91480246 275.90135065 289.68180011
 285.24397227 282.3382986  265.25936571 280.85583955 279.17911091
 281.41292229 286.41388163 284.89764716 287.76765383 285.07013777
 289.51825608 280.64544248 272.76096648 288.73115974 286.6413811
 300.56823501 280.13359709 294.5929726  271.16096729 282.98845791
 289.22845301 285.06134847 278.28668091 295.66512334 296.05335113
 272.76180889 281.80778783 285.64538842 290.51511126 289.52809675
 275.50673203 283.52458906 289.62365163 284.09221221 279.82460858
 287.27039063 277.72012727 288.1989676  284.33148625 295.46956236
 288.14295952 289.95698874 274.4301347  288.74578084 288.11913726
 266.55531852 280.49345618 282.91948942 275.06475641 275.32457301
 285.53918872 283.95667726 279.81024377 263.05977626 275.32381796
 278.71179677 279.34014503 283.74232535 281.96856728 287.17520108
 286.41621999 283.87109631 277.94726014 268.43235513 284.87547696
 283.1490341  296.90857144 278.16865192 294.14777797 270.58047935
 280.82142567 287.46400552 286.49856349 275.17186884 294.41301873
 293.36593818 270.89753441 280.08922007 281.33109106 288.24414721
 285.06195506 274.58598214 282.81489935 283.66841544 281.44521958
 275.82786619 284.64140569 278.20338067 283.79354028 286.11691119
 290.35519116 287.70929868 286.5131076  271.45070885 289.07774921
 286.66654707 286.39383233 268.31202024 277.01557176 282.24814528
 273.75990725 276.63820006 286.24771755 284.14433033 278.02349887
 265.77977057 279.12041516 281.03548753 277.33684583 284.37173294
 281.61799767 287.70563946 286.23941816 285.28350788 277.7141618
 266.50676028 284.00300734 280.91024561 297.04222521 279.5054547
 293.96237574 270.91490754 280.59602161 285.60043685 288.40595533
 275.36545551 293.29065443 291.6985524  269.37408402 281.68799995
 281.92602845 288.17232217 287.71426632 278.77773547 282.32051034
 286.81655911 287.62338824 290.08140743 289.13125718 273.41585363
 288.14314432 288.76181174]
Unique values in column AVG_READING_4_SCORE are: [207.9635172           nan 206.21271553 208.63445839 196.76441412
 213.48089033 222.41759863 206.38905171 178.55761165 204.88260635
 206.84417466 200.8802722  219.76325754 222.85293898 211.56230728
 196.76226784 228.38002678 209.64549669 223.16007568 218.30170917
 201.52932784 216.89807921 222.30141905 220.03496306 223.46613952
 219.39046832 204.53591068 211.74092082 214.35808554 225.23908328
 215.26834149 219.9400977  203.41619026 212.53139406 212.39431104
 217.33039276 213.45728593 212.69538584 213.1469347  224.1745453
 221.18555587 210.92076748 206.52978843 208.83771585 201.91259067
 221.65324325 231.59830462 212.00256329 181.62699047 207.29760937
 209.81870389 199.70168159 223.0452103  222.18488003 217.53088006
 204.22663027 225.4044552  214.92988693 225.3098605  216.501398
 221.83011422 204.30181534 216.18255868 226.14905681 207.59793006
 225.71564135 205.94860526 215.77921569 216.83746284 219.51182151
 214.44208659 218.02751787 210.44903886 212.40378272 216.86201241
 215.40919133 218.35272838 216.84696707 216.44325123 224.34723178
 219.01077962 223.35344268 206.88002955 205.34727538 212.88179718
 205.91658774 229.38114278 224.30355841 190.51807306 214.40459757
 214.81843752 207.58544266 220.21761699 221.88034682 223.33064085
 221.97833138 219.04206753 206.64044981 224.50827816 217.21117538
 233.74841032 218.61331956 225.25851437 202.79332806 220.17176716
 224.16286603 221.56523925 209.12916185 207.50117018 222.44505472
 221.63403978 223.59155804 222.43596538 213.32841559 219.93691829
 220.63639333 219.6235053  213.85885454 213.69391762 216.9322417
 221.51418055 226.9612274  225.0094358  223.6559327  218.77779412
 221.12975365 207.08384758 211.54715357 208.87280135 213.61530446
 205.6324371  223.66098196 228.34061496 223.92881141 188.3744785
 218.01448816 213.59721933 208.25956753 218.25988552 216.30428798
 220.40649113 223.27112982 220.14322971 219.04441733 204.72948752
 223.85949381 218.67375979 213.12783539 227.6042594  218.78905671
 222.6089623  205.46440681 222.26023013 222.74654163 220.61180207
 206.95968273 227.7895085  225.07332804 203.18531256 222.18820711
 221.22057966 221.64224574 221.86579908 213.57935707 217.61453525
 218.69842754 216.49401518 214.80772449 222.27317858 211.94754112
 214.80800562 219.27033842 226.12174663 223.34035919 221.09669513
 219.17952449 220.83342756 222.07516637 207.75203301 211.06131857
 207.14273664 217.0715289  206.51202648 223.65613    225.75301969
 225.83845909 190.78735569 219.46522218 214.43092054 209.57876764

In [62]:
for column_name in ed2_df.columns:
    print (f'{column_name} missing value % is', (1- ed2_df[column_name].count()/len(ed2_df))*100)

PRIMARY_KEY missing value % is 0.0
STATE missing value % is 0.0
YEAR missing value % is 0.0
ENROLL missing value % is 17.627345844504017
TOTAL_REVENUE missing value % is 14.209115281501338
FEDERAL_REVENUE missing value % is 14.209115281501338
STATE_REVENUE missing value % is 14.209115281501338
LOCAL_REVENUE missing value % is 14.209115281501338
TOTAL_EXPENDITURE missing value % is 14.209115281501338
INSTRUCTION_EXPENDITURE missing value % is 14.209115281501338
SUPPORT_SERVICES_EXPENDITURE missing value % is 14.209115281501338
OTHER_EXPENDITURE missing value % is 17.627345844504017
CAPITAL_OUTLAY_EXPENDITURE missing value % is 14.209115281501338
GRADES_PK_G missing value % is 11.595174262734586
GRADES_KG_G missing value % is 8.847184986595169
GRADES_4_G missing value % is 8.780160857908847
GRADES_8_G missing value % is 8.780160857908847
GRADES_12_G missing value % is 8.780160857908847
GRADES_1_8_G missing value % is 8.780160857908847
GRADES_9_12_G missing value % is 8.780160857908847
GRADES_ALL_G missing value % is 11.595174262734586
AVG_MATH_4_SCORE missing value % is 64.07506702412869
AVG_MATH_8_SCORE missing value % is 64.343163538874
AVG_READING_4_SCORE missing value % is 64.27613941018765
AVG_READING_8_SCORE missing value % is 66.62198391420911

In [63]:
# fill all floats with mean of total dataset
for column_name in ed2_df.columns:
    if ed2_df[column_name].dtype in ('float64',):
       ed2_df[column_name].fillna(ed2_df[column_name].mean(), inplace=True)

In [64]:
# check if there is any null values 
for column_name in ed2_df.columns:
    print (f'{column_name} missing value % is', (1- ed2_df[column_name].count()/len(ed2_df))*100)

PRIMARY_KEY missing value % is 0.0
STATE missing value % is 0.0
YEAR missing value % is 0.0
ENROLL missing value % is 0.0
TOTAL_REVENUE missing value % is 0.0
FEDERAL_REVENUE missing value % is 0.0
STATE_REVENUE missing value % is 0.0
LOCAL_REVENUE missing value % is 0.0
TOTAL_EXPENDITURE missing value % is 0.0
INSTRUCTION_EXPENDITURE missing value % is 0.0
SUPPORT_SERVICES_EXPENDITURE missing value % is 0.0
OTHER_EXPENDITURE missing value % is 0.0
CAPITAL_OUTLAY_EXPENDITURE missing value % is 0.0
GRADES_PK_G missing value % is 0.0
GRADES_KG_G missing value % is 0.0
GRADES_4_G missing value % is 0.0
GRADES_8_G missing value % is 0.0
GRADES_12_G missing value % is 0.0
GRADES_1_8_G missing value % is 0.0
GRADES_9_12_G missing value % is 0.0
GRADES_ALL_G missing value % is 0.0
AVG_MATH_4_SCORE missing value % is 0.0
AVG_MATH_8_SCORE missing value % is 0.0
AVG_READING_4_SCORE missing value % is 0.0
AVG_READING_8_SCORE missing value % is 0.0

In [65]:
ed2_df.head(100)

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,9.159308e+05,2678885.0,304177.0,1659028.0,715680.0,2653798.0,1481703.0,...,57948.0,58025.0,41167.0,471564.0,196386.0,676174.0,208.327876,252.187522,207.963517,263.661132
1,1992_ALASKA,ALASKA,1992,9.159308e+05,1049591.0,106780.0,720711.0,222100.0,972488.0,498362.0,...,9748.0,8789.0,6714.0,79117.0,30847.0,112335.0,234.768293,278.414711,218.866154,258.859712
2,1992_ARIZONA,ARIZONA,1992,9.159308e+05,3258079.0,297888.0,1369815.0,1590376.0,3401580.0,1435908.0,...,55433.0,49081.0,37410.0,437127.0,175210.0,614881.0,215.253932,265.366278,206.212716,262.169895
3,1992_ARKANSAS,ARKANSAS,1992,9.159308e+05,1711959.0,178571.0,958785.0,574603.0,1743022.0,964323.0,...,34632.0,36011.0,27651.0,281338.0,123113.0,405259.0,210.206028,256.312090,208.634458,264.619665
4,1992_CALIFORNIA,CALIFORNIA,1992,9.159308e+05,26260025.0,2072470.0,16546514.0,7641041.0,27138832.0,14358922.0,...,418418.0,363296.0,270675.0,3286034.0,1372011.0,4717112.0,208.398961,260.892247,196.764414,263.661132
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1993_TENNESSEE,TENNESSEE,1993,8.446680e+05,3268642.0,334410.0,1535027.0,1399205.0,3286481.0,1969619.0,...,65646.0,64124.0,47668.0,534579.0,236542.0,780663.0,234.768293,278.414711,218.866154,263.661132
96,1993_TEXAS,TEXAS,1993,3.535333e+06,20267205.0,1233446.0,9919561.0,9114198.0,18574871.0,8914245.0,...,284394.0,274208.0,178889.0,2291961.0,927209.0,3339616.0,234.768293,278.414711,218.866154,263.661132
97,1993_UTAH,UTAH,1993,4.623230e+05,1638305.0,116791.0,928596.0,592918.0,1665011.0,881924.0,...,35467.0,38031.0,31692.0,287657.0,137235.0,427582.0,234.768293,278.414711,218.866154,263.661132
98,1993_VERMONT,VERMONT,1993,9.745400e+04,837540.0,34179.0,216778.0,586583.0,809853.0,405876.0,...,8457.0,7496.0,6227.0,65038.0,27377.0,94439.0,234.768293,278.414711,218.866154,263.661132
99,1993_VIRGINIA,VIRGINIA,1993,1.032842e+06,5918536.0,365601.0,2358711.0,3194224.0,5955333.0,3121277.0,...,81615.0,78443.0,60314.0,652886.0,278009.0,934081.0,234.768293,278.414711,218.866154,263.661132

In [66]:
#3 again read data
ed3_df = pd.read_sql_query('SELECT * FROM useducation',con=engine)

In [67]:
ed3_df['YEAR'].unique()

array([1992, 2001, 1993, 2016, 1994, 1995, 1996, 1997, 1998, 1999, 2017,
       2000, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015])

In [68]:
# now fill nulls with mean of the values in same year  
# fill all floats with mean of total dataset
for year_var in ed3_df['YEAR'].unique():
    for column_name in ed3_df.columns:
      if ed3_df[column_name].dtype in ('float64',):
          ed3_df.loc[(ed3_df['YEAR'] == year_var) & (ed3_df[column_name].isnull()), column_name] = ed3_df[ed3_df['YEAR'] == year_var][column_name].mean()

In [69]:
ed3_df[ed3_df['YEAR']== 1992].head(100)

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,NaN,2.678885e+06,3.041770e+05,1.659028e+06,7.156800e+05,2.653798e+06,1.481703e+06,...,57948.0,58025.0,41167.0,471564.0,196386.0,6.761740e+05,208.327876,252.187522,207.963517,263.307067
1,1992_ALASKA,ALASKA,1992,NaN,1.049591e+06,1.067800e+05,7.207110e+05,2.221000e+05,9.724880e+05,4.983620e+05,...,9748.0,8789.0,6714.0,79117.0,30847.0,1.123350e+05,218.410116,266.360319,212.712256,258.859712
2,1992_ARIZONA,ARIZONA,1992,NaN,3.258079e+06,2.978880e+05,1.369815e+06,1.590376e+06,3.401580e+06,1.435908e+06,...,55433.0,49081.0,37410.0,437127.0,175210.0,6.148810e+05,215.253932,265.366278,206.212716,262.169895
3,1992_ARKANSAS,ARKANSAS,1992,NaN,1.711959e+06,1.785710e+05,9.587850e+05,5.746030e+05,1.743022e+06,9.643230e+05,...,34632.0,36011.0,27651.0,281338.0,123113.0,4.052590e+05,210.206028,256.312090,208.634458,264.619665
4,1992_CALIFORNIA,CALIFORNIA,1992,NaN,2.626002e+07,2.072470e+06,1.654651e+07,7.641041e+06,2.713883e+07,1.435892e+07,...,418418.0,363296.0,270675.0,3286034.0,1372011.0,4.717112e+06,208.398961,260.892247,196.764414,263.307067
5,1992_COLORADO,COLORADO,1992,NaN,3.185173e+06,1.632530e+05,1.307986e+06,1.713934e+06,3.264826e+06,1.642466e+06,...,50648.0,45025.0,34533.0,394904.0,160299.0,5.626130e+05,221.023429,272.398433,213.480890,266.419687
6,1992_CONNECTICUT,CONNECTICUT,1992,NaN,3.834302e+06,1.435420e+05,1.342539e+06,2.348221e+06,3.721338e+06,2.148041e+06,...,38058.0,33691.0,28366.0,304284.0,126917.0,4.369320e+05,226.798480,273.739345,222.417599,264.713904
7,1992_DELAWARE,DELAWARE,1992,NaN,6.452330e+05,4.594500e+04,4.209420e+05,1.783460e+05,6.387840e+05,3.727220e+05,...,8272.0,8012.0,6129.0,67495.0,28338.0,9.629600e+04,217.899972,262.868585,206.389052,261.577921
8,1992_DISTRICT_OF_COLUMBIA,DISTRICT_OF_COLUMBIA,1992,NaN,7.094800e+05,6.474900e+04,0.000000e+00,6.447310e+05,7.428930e+05,3.291600e+05,...,5832.0,5000.0,3433.0,47009.0,18173.0,7.000000e+04,192.600553,234.924621,178.557612,265.976765
9,1992_FLORIDA,FLORIDA,1992,NaN,1.150630e+07,7.884200e+05,5.683949e+06,5.033930e+06,1.130564e+07,5.166374e+06,...,164416.0,142372.0,100835.0,1276685.0,511557.0,1.819706e+06,213.689751,259.908848,204.882606,262.118986
10,1992_GEORGIA,GEORGIA,1992,NaN,5.536901e+06,3.987010e+05,2.798674e+06,2.339526e+06,5.535942e+06,3.043984e+06,...,99648.0,92374.0,63646.0,787599.0,315539.0,1.106441e+06,215.594906,259.359434,206.844175,263.307067
11,1992_HAWAII,HAWAII,1992,NaN,9.968090e+05,7.127300e+04,9.034430e+05,2.209300e+04,1.040121e+06,5.361150e+05,...,13754.0,11750.0,9051.0,107242.0,43882.0,1.516490e+05,214.056666,257.410887,200.880272,263.307067
12,1992_IDAHO,IDAHO,1992,NaN,8.593290e+05,6.913800e+04,5.319120e+05,2.582790e+05,8.861610e+05,4.735050e+05,...,18607.0,18880.0,14593.0,146573.0,66541.0,2.143450e+05,221.562534,275.090294,212.712256,263.307067
13,1992_ILLINOIS,ILLINOIS,1992,NaN,9.748650e+06,5.970770e+05,3.073178e+06,6.078395e+06,9.850560e+06,5.010400e+06,...,133120.0,134317.0,106475.0,1111167.0,495562.0,1.646411e+06,218.410116,266.360319,212.712256,263.307067
14,1992_INDIANA,INDIANA,1992,NaN,5.060274e+06,2.570440e+05,2.578149e+06,2.225081e+06,5.182754e+06,2.598925e+06,...,73760.0,75477.0,62234.0,601890.0,278161.0,8.832760e+05,221.037742,270.098944,219.763258,263.307067
15,1992_IOWA,IOWA,1992,NaN,2.663934e+06,1.256650e+05,1.176205e+06,1.362064e+06,2.795774e+06,1.446478e+06,...,37692.0,36892.0,33057.0,299253.0,138907.0,4.427520e+05,229.884078,283.360009,222.852939,263.307067
16,1992_KANSAS,KANSAS,1992,NaN,2.245348e+06,1.216250e+05,9.031990e+05,1.220524e+06,2.234915e+06,1.165749e+06,...,36013.0,33288.0,26706.0,284143.0,120960.0,4.074940e+05,218.410116,266.360319,212.712256,263.307067
17,1992_KENTUCKY,KENTUCKY,1992,NaN,2.642902e+06,2.899020e+05,1.643109e+06,7.098910e+05,2.518082e+06,1.343438e+06,...,49666.0,49993.0,38029.0,400849.0,181786.0,5.971990e+05,215.048158,262.241282,211.562307,263.307067
18,1992_LOUISIANA,LOUISIANA,1992,NaN,3.341253e+06,3.678220e+05,1.848734e+06,1.124697e+06,3.362853e+06,1.888349e+06,...,61125.0,55942.0,38368.0,490112.0,196891.0,6.984420e+05,204.140211,249.983926,196.762268,263.307067
19,1992_MAINE,MAINE,1992,NaN,1.206819e+06,7.316000e+04,5.116540e+05,6.220050e+05,1.228869e+06,6.853500e+05,...,17154.0,15969.0,13882.0,135320.0,59289.0,1.958820e+05,231.638840,278.635384,228.380027,263.307067
20,1992_MARYLAND,MARYLAND,1992,NaN,4.658498e+06,2.283360e+05,1.778834e+06,2.651328e+06,4.698374e+06,2.628891e+06,...,60287.0,52815.0,40426.0,472622.0,189795.0,6.784980e+05,217.317708,264.825493,209.645497,263.307067
21,1992_MASSACHUSETTS,MASSACHUSETTS,1992,NaN,5.517659e+06,2.739460e+05,1.439051e+06,3.804662e+06,5.245560e+06,2.751871e+06,...,66822.0,60702.0,52425.0,536029.0,230299.0,7.770500e+05,226.597918,272.783201,223.160076,263.307067
22,1992_MICHIGAN,MICHIGAN,1992,NaN,9.963137e+06,5.379170e+05,2.539380e+06,6.885840e+06,1.017069e+07,4.681327e+06,...,118963.0,114282.0,90655.0,968910.0,419351.0,1.398802e+06,219.878352,267.353194,212.712256,263.307067
23,1992_MINNESOTA,MINNESOTA,1992,NaN,4.684684e+06,1.940920e+05,2.380754e+06,2.109838e+06,4.981125e+06,2.534882e+06,...,62606.0,59810.0,53813.0,500938.0,224426.0,7.317580e+05,228.493596,282.392205,218.301709,263.307067
24,1992_MISSISSIPPI,MISSISSIPPI,1992,NaN,1.684706e+06,2.777060e+05,9.011990e+05,5.058010e+05,1.691990e+06,9.561040e+05,...,39839.0,38132.0,26328.0,321614.0,129554.0,4.519860e+05,201.828261,246.458035,201.529328,263.307067
25,1992_MISSOURI,MISSOURI,1992,NaN,4.043682e+06,2.551940e+05,1.903124e+06,1.885364e+06,4.197600e+06,2.168135e+06,...,67098.0,64546.0,50534.0,531337.0,235437.0,7.857220e+05,222.215600,271.131545,216.898079,263.307067
26,1992_MONTANA,MONTANA,1992,NaN,8.289830e+05,6.994700e+04,3.374550e+05,4.215810e+05,7.810090e+05,4.122190e+05,...,12839.0,12124.0,10019.0,102124.0,44449.0,1.471270e+05,218.410116,266.360319,222.301419,263.307067
27,1992_NEBRASKA,NEBRASKA,1992,NaN,1.542413e+06,8.542300e+04,4.922560e+05,9.647340e+05,1.534046e+06,9.091590e+05,...,22133.0,21379.0,18999.0,177432.0,79975.0,2.605410e+05,225.332648,277.654523,220.034963,263.307067
28,1992_NEVADA,NEVADA,1992,NaN,1.097076e+06,4.501800e+04,7.240320e+05,3.280260e+05,1.251651e+06,5.726230e+05,...,18487.0,16250.0,12242.0,145687.0,57605.0,2.043300e+05,218.410116,266.360319,212.712256,263.307067
29,1992_NEW_HAMPSHIRE,NEW_HAMPSHIRE,1992,NaN,1.063391e+06,3.102000e+04,8.629600e+04,9.460750e+05,1.066647e+06,5.811230e+05,...,15611.0,13537.0,10752.0,123475.0,47999.0,1.724790e+05,229.664564,278.216326,223.466140,263.307067
30,1992_NEW_JERSEY,NEW_JERSEY,1992,NaN,1.081469e+07,4.160630e+05,4.504718e+06,5.893908e+06,1.045234e+07,6.042936e+06,...,82909.0,77779.0,67353.0,671021.0,295337.0,9.754810e+05,227.148047,271.905561,219.390468,263.307067
31,1992_NEW_MEXICO,NEW_MEXICO,1992,NaN,1.330091e+06,1.615200e+05,9.906530e+05,1.779180e+05,1.339829e+06,6.832530e+05,...,24447.0,21690.0,16027.0,191623.0,80105.0,2.738000e+05,213.299090,259.606718,204.535911,263.307067
32,1992_NEW_YORK,NEW_YORK,1992,NaN,2.163018e+07,1.172030e+06,8.697663e+06,1.176049e+07,2.281561e+07,1.328897e+07,...,197698.0,184815.0,142822.0,1585404.0,727840.0,2.344534e+06,218.445535,266.422300,211.740921,263.307067
33,1992_NORTH_CAROLINA,NORTH_CAROLINA,1992,NaN,5.236099e+06,3.891450e+05,3.283378e+06,1.563576e+06,5.418687e+06,2.847638e+06,...,85244.0,84291.0,63427.0,695047.0,303507.0,1.004673e+06,212.884490,258.405375,214.358086,263.307067
34,1992_NORTH_DAKOTA,NORTH_DAKOTA,1992,NaN,5.594810e+05,5.147600e+04,2.426930e+05,2.653120e+05,5.537320e+05,3.150090e+05,...,9570.0,9102.0,8014.0,75082.0,34165.0,1.098870e+05,228.662815,283.213075,225.239083,263.307067
35,1992_OHIO,OHIO,1992,NaN,9.285961e+06,4.726040e+05,3.631703e+06,5.181654e+06,9.483822e+06,5.172782e+06,...,137839.0,137075.0,116085.0,1126405.0,511330.0,1.647635e+06,218.711935,268.124198,212.712256,263.307067
37,1992_OKLAHOMA,OKLAHOMA,1992,NaN,2.396705e+06,2.116270e+05,1.470516e+06,7.145620e+05,2.515272e+06,1.283577e+06,...,48793.0,44163.0,33346.0,387659.0,157824.0,5.503420e+05,220.319806,268.131990,212.712256,263.307067
38,1992_OREGON,OREGON,1992,NaN,2.773959e+06,1.635440e+05,7.883090e+05,1.822106e+06,2.898210e+06,1.556770e+06,...,41443.0,39610.0,31920.0,325128.0,144002.0,4.699010e+05,218.410116,266.360319,212.712256,263.307067
39,1992_PENNSYLVANIA,PENNSYLVANIA,1992,NaN,1.125725e+07,6.581390e+05,4.227323e+06,6.371790e+06,1.153925e+07,6.075381e+06,...,131248.0,126293.0,108244.0,1063552.0,486354.0,1.554322e+06,224.305732,271.378439,215.268341,263.307067
40,1992_RHODE_ISLAND,RHODE_ISLAND,1992,NaN,8.830730e+05,4.354500e+04,3.298100e+05,5.097180e+05,8.634040e+05,5.567870e+05,...,11129.0,10204.0,8244.0,90758.0,37931.0,1.291870e+05,215.449248,265.907109,219.940098,263.307067
41,1992_SOUTH_CAROLINA,SOUTH_CAROLINA,1992,NaN,2.842626e+06,2.499030e+05,1.350148e+06,1.242575e+06,2.922293e+06,1.544232e+06,...,51081.0,49562.0,34615.0,415759.0,173159.0,5.959630e+05,212.496714,260.772544,203.416190,263.307067
42,1992_SOUTH_DAKOTA,SOUTH_DAKOTA,1992,NaN,5.516680e+05,6.067100e+04,1.478340e+05,3.431630e+05,5.931260e+05,3.205610e+05,...,10645.0,10498.0,8259.0,85823.0,36326.0,1.228540e+05,218.410116,266.360319,212.712256,263.307067
43,1992_TENNESSEE,TENNESSEE,1992,NaN,3.080490e+06,3.085710e+05,1.305381e+06,1.466538e+06,3.132516e+06,1.830264e+06,...,65195.0,63358.0,49639.0,530221.0,233430.0,7.732640e+05,210.948227,258.828048,212.531394,263.307067
44,1992_TEXAS,TEXAS,1992,NaN,1.626418e+07,1.160185e+06,6.706959e+06,8.397036e+06,1.611908e+07,7.961379e+06,...,282693.0,261053.0,180206.0,2258666.0,907423.0,3.279286e+06,217.918744,264.592828,212.394311,263.307067
45,1992_UTAH,UTAH,1992,NaN,1.555799e+06,1.053490e+05,8.725100e+05,5.779400e+05,1.547980e+06,8.415520e+05,...,35956.0,36813.0,28775.0,288781.0,130082.0,4.214740e+05,224.042248,274.343177,217.330393,263.307067
46,1992_VERMONT,VERMONT,1992,NaN,8.123770e+05,3.175700e+04,2.041630e+05,5.764570e+05,8.003770e+05,3.866990e+05,...,8329.0,7227.0,5573.0,64107.0,24099.0,8.998600e+04,218.410116,266.360319,212.712256,263.307067
47,1992_VIRGINIA,VIRGINIA,1992,NaN,5.631293e+06,3.139710e+05,2.180133e+06,3.137189e+06,5.744469e+06,2.982862e+06,...,79821.0,76775.0,60854.0,645925.0,273971.0,9.218720e+05,220.762964,267.863726,213.457286,263.307067
48,1992_WASHINGTON,WASHINGTON,1992,NaN,4.870832e+06,2.630530e+05,3.467779e+06,1.140000e+06,5.360834e+06,2.587181e+06,...,74098.0,67285.0,53986.0,578106.0,244732.0,8.279130e+05,218.410116,266.360319,212.695386,263.307067
49,1992_WEST_VIRGINIA,WEST_VIRGINIA,1992,NaN,1.585099e+06,1.301170e+05,1.021803e+06,4.331790e+05,1.587968e+06,8.351860e+05,...,23556.0,24791.0,21844.0,191101.0,96241.0,2.896500e+05,215.268928,259.086448,213.146935,263.307067
50,1992_WISCONSIN,WISCONSIN,1992,NaN,4.993909e+06,2.177230e+05,2.205439e+06,2.570747e+06,5.181471e+06,2.914442e+06,...,63365.0,60783.0,55543.0,507607.0,239952.0,7.637860e+05,228.692001,277.879135,224.174545,263.307067
51,1992_WYOMING,WYOMING,1992,NaN,6.297480e+05,3.171400e+04,3.142160e+05,2.838180e+05,6.249410e+05,3.399530e+05,...,8049.0,8078.0,6613.0,64614.0,28515.0,7.267347e+05,225.377592,275.080076,221.185556,263.307067
1421,1992_AMERICAN_SAMOA,AMERICAN_SAMOA,1992,NaN,4.572764e+06,2.970296e+05,2.088314e+06,2.187420e+06,4.653591e+06,2.454000e+06,...,981.0,886.0,748.0,7969.0,3355.0,1.278600e+04,218.410116,266.360319,212.712256,263.307067
1422,1992_GUAM,GUAM,1992,NaN,4.572764e+06,2.970296e+05,2.088314e+06,2.187420e+06,4.653591e+06,2.454000e+06,...,2392.0,2061.0,1115.0,19072.0,7631.0,2.736000e+04,218.410116,266.360319,212.712256,263.307067
1423,1992_COMMONWEALTH_OF_MARIANAS,COMMONWEALTH_OF_MARIANAS,1992,NaN,4.572764e+06,2.970296e+05,2.088314e+06,2.187420e+06,4.653591e+06,2.454000e+06,...,661.0,437.0,311.0,4878.0,1953.0,7.254000e+03,218.410116,266.360319,212.712256,263.307067
1424,1992_PUERTO_RICO,PUERTO_RICO,1992,NaN,4.572764e+06,2.970296e+05,2.088314e+06,2.187420e+06,4.653591e+06,2.454000e+06,...,52944.0,50913.0,32344.0,423308.0,163573.0,5.869700e+05,218.410116,266.360319,212.712256,263.307067
1425,1992_VIRGIN_ISLANDS,VIRGIN_ISLANDS,1992,NaN,4.572764e+06,2.970296e+05,2.088314e+06,2.187420e+06,4.653591e+06,2.454000e+06,...,1878.0,1549.0,1117.0,14422.0,5590.0,7.267347e+05,218.410116,266.360319,212.712256,263.307067

In [70]:
# check if there is any null values 
for column_name in ed3_df.columns:
    print (f'{column_name} missing value % is', (1- ed3_df[column_name].count()/len(ed3_df))*100)
# still missing values as few years not havingg any value

PRIMARY_KEY missing value % is 0.0
STATE missing value % is 0.0
YEAR missing value % is 0.0
ENROLL missing value % is 7.1715817694369965
TOTAL_REVENUE missing value % is 3.4182305630026777
FEDERAL_REVENUE missing value % is 3.4182305630026777
STATE_REVENUE missing value % is 3.4182305630026777
LOCAL_REVENUE missing value % is 3.4182305630026777
TOTAL_EXPENDITURE missing value % is 3.4182305630026777
INSTRUCTION_EXPENDITURE missing value % is 3.4182305630026777
SUPPORT_SERVICES_EXPENDITURE missing value % is 3.4182305630026777
OTHER_EXPENDITURE missing value % is 7.1715817694369965
CAPITAL_OUTLAY_EXPENDITURE missing value % is 3.4182305630026777
GRADES_PK_G missing value % is 6.836461126005366
GRADES_KG_G missing value % is 6.836461126005366
GRADES_4_G missing value % is 6.836461126005366
GRADES_8_G missing value % is 6.836461126005366
GRADES_12_G missing value % is 6.836461126005366
GRADES_1_8_G missing value % is 6.836461126005366
GRADES_9_12_G missing value % is 6.836461126005366
GRADES_ALL_G missing value % is 6.836461126005366
AVG_MATH_4_SCORE missing value % is 57.64075067024128
AVG_MATH_8_SCORE missing value % is 57.64075067024128
AVG_READING_4_SCORE missing value % is 57.64075067024128
AVG_READING_8_SCORE missing value % is 57.64075067024128

In [73]:

ed_df = pd.read_sql_query('SELECT * FROM useducation',con=engine)
#ed5_df.interpolate(method ='linear', limit_direction ='forward') 
#ed5_df['AVG_READING_8_SCORE']=ed5_df['AVG_READING_8_SCORE'].interpolate(method ='linear', limit_direction ='forward')
ed4_df_f = ed_df.interpolate(method='linear')
ed4_df = ed4_df_f.interpolate(method='linear',limit_direction='backward')

/var/folders/9_/1k3n4lms2cg9br6mjz1f_cq80000gp/T/ipykernel_73212/3710050292.py:4: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  ed4_df_f = ed_df.interpolate(method='linear')
/var/folders/9_/1k3n4lms2cg9br6mjz1f_cq80000gp/T/ipykernel_73212/3710050292.py:5: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  ed4_df = ed4_df_f.interpolate(method='linear',limit_direction='backward')

In [74]:
# check if there is any null values 
for column_name in ed4_df.columns:
    print (f'{column_name} missing value % is', (1- ed4_df[column_name].count()/len(ed4_df))*100)

PRIMARY_KEY missing value % is 0.0
STATE missing value % is 0.0
YEAR missing value % is 0.0
ENROLL missing value % is 0.0
TOTAL_REVENUE missing value % is 0.0
FEDERAL_REVENUE missing value % is 0.0
STATE_REVENUE missing value % is 0.0
LOCAL_REVENUE missing value % is 0.0
TOTAL_EXPENDITURE missing value % is 0.0
INSTRUCTION_EXPENDITURE missing value % is 0.0
SUPPORT_SERVICES_EXPENDITURE missing value % is 0.0
OTHER_EXPENDITURE missing value % is 0.0
CAPITAL_OUTLAY_EXPENDITURE missing value % is 0.0
GRADES_PK_G missing value % is 0.0
GRADES_KG_G missing value % is 0.0
GRADES_4_G missing value % is 0.0
GRADES_8_G missing value % is 0.0
GRADES_12_G missing value % is 0.0
GRADES_1_8_G missing value % is 0.0
GRADES_9_12_G missing value % is 0.0
GRADES_ALL_G missing value % is 0.0
AVG_MATH_4_SCORE missing value % is 0.0
AVG_MATH_8_SCORE missing value % is 0.0
AVG_READING_4_SCORE missing value % is 0.0
AVG_READING_8_SCORE missing value % is 0.0

In [76]:
# compare 3 df
def print_missing(df):
    for column_name in df.columns:
        print (f'{column_name} missing value % is', (1- df[column_name].count()/len(ed4_df))*100)
# ed2_df ed3_df ed5_df
print('dataframe filled with total means')
print_missing(ed2_df)
print('dataframe filled with total means by year')
print_missing(ed3_df)
print('dataframe filled with interpolation')
print_missing(ed4_df)

dataframe filled with total means
PRIMARY_KEY missing value % is 0.0
STATE missing value % is 0.0
YEAR missing value % is 0.0
ENROLL missing value % is 0.0
TOTAL_REVENUE missing value % is 0.0
FEDERAL_REVENUE missing value % is 0.0
STATE_REVENUE missing value % is 0.0
LOCAL_REVENUE missing value % is 0.0
TOTAL_EXPENDITURE missing value % is 0.0
INSTRUCTION_EXPENDITURE missing value % is 0.0
SUPPORT_SERVICES_EXPENDITURE missing value % is 0.0
OTHER_EXPENDITURE missing value % is 0.0
CAPITAL_OUTLAY_EXPENDITURE missing value % is 0.0
GRADES_PK_G missing value % is 0.0
GRADES_KG_G missing value % is 0.0
GRADES_4_G missing value % is 0.0
GRADES_8_G missing value % is 0.0
GRADES_12_G missing value % is 0.0
GRADES_1_8_G missing value % is 0.0
GRADES_9_12_G missing value % is 0.0
GRADES_ALL_G missing value % is 0.0
AVG_MATH_4_SCORE missing value % is 0.0
AVG_MATH_8_SCORE missing value % is 0.0
AVG_READING_4_SCORE missing value % is 0.0
AVG_READING_8_SCORE missing value % is 0.0
dataframe filled with total means by year
PRIMARY_KEY missing value % is 0.0
STATE missing value % is 0.0
YEAR missing value % is 0.0
ENROLL missing value % is 7.1715817694369965
TOTAL_REVENUE missing value % is 3.4182305630026777
FEDERAL_REVENUE missing value % is 3.4182305630026777
STATE_REVENUE missing value % is 3.4182305630026777
LOCAL_REVENUE missing value % is 3.4182305630026777
TOTAL_EXPENDITURE missing value % is 3.4182305630026777
INSTRUCTION_EXPENDITURE missing value % is 3.4182305630026777
SUPPORT_SERVICES_EXPENDITURE missing value % is 3.4182305630026777
OTHER_EXPENDITURE missing value % is 7.1715817694369965
CAPITAL_OUTLAY_EXPENDITURE missing value % is 3.4182305630026777
GRADES_PK_G missing value % is 6.836461126005366
GRADES_KG_G missing value % is 6.836461126005366
GRADES_4_G missing value % is 6.836461126005366
GRADES_8_G missing value % is 6.836461126005366
GRADES_12_G missing value % is 6.836461126005366
GRADES_1_8_G missing value % is 6.836461126005366
GRADES_9_12_G missing value % is 6.836461126005366
GRADES_ALL_G missing value % is 6.836461126005366
AVG_MATH_4_SCORE missing value % is 57.64075067024128
AVG_MATH_8_SCORE missing value % is 57.64075067024128
AVG_READING_4_SCORE missing value % is 57.64075067024128
AVG_READING_8_SCORE missing value % is 57.64075067024128
dataframe filled with interpolation
PRIMARY_KEY missing value % is 0.0
STATE missing value % is 0.0
YEAR missing value % is 0.0
ENROLL missing value % is 0.0
TOTAL_REVENUE missing value % is 0.0
FEDERAL_REVENUE missing value % is 0.0
STATE_REVENUE missing value % is 0.0
LOCAL_REVENUE missing value % is 0.0
TOTAL_EXPENDITURE missing value % is 0.0
INSTRUCTION_EXPENDITURE missing value % is 0.0
SUPPORT_SERVICES_EXPENDITURE missing value % is 0.0
OTHER_EXPENDITURE missing value % is 0.0
CAPITAL_OUTLAY_EXPENDITURE missing value % is 0.0
GRADES_PK_G missing value % is 0.0
GRADES_KG_G missing value % is 0.0
GRADES_4_G missing value % is 0.0
GRADES_8_G missing value % is 0.0
GRADES_12_G missing value % is 0.0
GRADES_1_8_G missing value % is 0.0
GRADES_9_12_G missing value % is 0.0
GRADES_ALL_G missing value % is 0.0
AVG_MATH_4_SCORE missing value % is 0.0
AVG_MATH_8_SCORE missing value % is 0.0
AVG_READING_4_SCORE missing value % is 0.0
AVG_READING_8_SCORE missing value % is 0.0

In [78]:
# data filled by year is still having missing values 
# now display head and see 
print('dataframe filled with total means')
ed2_df.head()
print('dataframe filled with total means by year')
ed3_df.head()
print('dataframe filled with interpolation')
ed4_df.head()

dataframe filled with total means
dataframe filled with total means by year
dataframe filled with interpolation

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,89711.0,2678885.0,304177.0,1659028.0,715680.0,2653798.0,1481703.0,...,57948.0,58025.0,41167.0,471564.0,196386.0,676174.0,208.327876,252.187522,207.963517,258.859712
1,1992_ALASKA,ALASKA,1992,89711.0,1049591.0,106780.0,720711.0,222100.0,972488.0,498362.0,...,9748.0,8789.0,6714.0,79117.0,30847.0,112335.0,211.790904,258.776900,207.088116,258.859712
2,1992_ARIZONA,ARIZONA,1992,89711.0,3258079.0,297888.0,1369815.0,1590376.0,3401580.0,1435908.0,...,55433.0,49081.0,37410.0,437127.0,175210.0,614881.0,215.253932,265.366278,206.212716,262.169895
3,1992_ARKANSAS,ARKANSAS,1992,89711.0,1711959.0,178571.0,958785.0,574603.0,1743022.0,964323.0,...,34632.0,36011.0,27651.0,281338.0,123113.0,405259.0,210.206028,256.312090,208.634458,264.619665
4,1992_CALIFORNIA,CALIFORNIA,1992,89711.0,26260025.0,2072470.0,16546514.0,7641041.0,27138832.0,14358922.0,...,418418.0,363296.0,270675.0,3286034.0,1372011.0,4717112.0,208.398961,260.892247,196.764414,265.519676